services:
  - type: web
    name: ems-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    plan: free
    region: ohio
    healthCheckPath: /actuator/health
    envVars:
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: "3306"
      - key: MYSQL_DB
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_SSL_MODE
        value: "REQUIRED"
      - key: MONGO_URI
        sync: false
